version: '3.9'
services:
  db-mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - dbdata-volume:/data/db
    networks: 
      - test-bridge
  
  wallet-app:
    build: .
    restart: unless-stopped
    ports: 
      - 3001:3001
    environment:
      - URL_MONGODB=$URL_MONGODB
      - JWT_SECRET=$JWT_SECRET
      - PORT=$PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-mongo
    links:
      - db-mongo
    networks: 
      - test-bridge
    
volumes:
  dbdata-volume:

networks:
  test-bridge:
    external: true

    

  